### ISSUE TITLE
[NumberGuesser] Списано?

### ISSUE THREAD

**Issue by pavel-b-novikov** [TrofimovaEkaterina/nsudotnet#1]
Множество комментариев не позволило скрыть LinkedList, который использует @Phoenix-616

**Comment by TrofimovaEkaterina** [comment]
Павел Борисович, подскажите, что не так с LinkedList?

**Comment by pavel-b-novikov** [comment]
С LinkedList все так, но необходимо обосновать необходимость его использования здесь. Особенно вместо изначально предлагавшегося массива

**Comment by TrofimovaEkaterina** [comment]
Особой необходимости нет. Можно спокойно использовать массив. Список просто позволяет не ограничивать историю игры (хотя 1000 позиций должно быть более чем достаточно). LinkedList больше всплыл как привычка из Java. 
Исправлено на массив.

**Comment by pavel-b-novikov** [comment]
LinkedList - не единственный вариант. Какие еще есть? В чем специфика?

**Comment by TrofimovaEkaterina** [comment]
Еще один вариант List<T>. В его основе лежит массив, который увеличивается по мере необходимости. Соответственно есть возможность быстро обратиться к нужному элементу по индексу. 
LinkedList<T> представляет собой список LinkedListNode<T>. Каждая такая нода имеет ссылку на предыдущую и следующую ноды. За счет этого можно за константное время вставлять и удалять элементы из середины и начала списка.
Есть еще ArrayList. Он похож на List<T>, но не типизирован и может хранить объекты разных классов.

**Comment by pavel-b-novikov** [comment]
Вижу что соображаете, пойдет
