### ISSUE TITLE
[LinesCounter] Внутристрочные комментарии

### ISSUE THREAD

**Issue by pavel-b-novikov** [TrofimovaEkaterina/nsudotnet#3]
Не учитываются. Это неправильно

**Comment by TrofimovaEkaterina** [comment]
Не совсем поняла, что Вы имеете ввиду.  Если в строке есть комментарий, то мы ее сразу не учитываем? Приведите, пожалуйста, пример.

**Comment by pavel-b-novikov** [comment]
```csharp

/**
* Hi, I am
* Multiline comment.
Everything between slash-start and star-slash
is being ignored during compilation
*/
public static void Main(...) { ... }

```

**Comment by pavel-b-novikov** [comment]
А, я написал внутристрочные? Извините, многострочные

**Comment by TrofimovaEkaterina** [comment]
Исправлено

**Comment by pavel-b-novikov** [comment]
```str = str.Substring(str.LastIndexOf("*/") + 2);```

~~Аээ.. эт зачем?~~ а, понял

**Comment by pavel-b-novikov** [comment]
Все очень косо и криво, но ладно
