### ISSUE TITLE
[Enigma] Совершенно точно списано

### ISSUE THREAD

**Issue by pavel-b-novikov** [TrofimovaEkaterina/nsudotnet#5]
У @Phoenix-616 абсолютно та же логика написания задачи и тот же уровень понимания происходящего. Строка-в-строку. У вас или общий мозг или кто-то у кого-то списал. Третьего тут быть не может.

**Comment by TrofimovaEkaterina** [comment]
В этой задаче у меня возникла проблема при кодировании - моя реализация позволяла кодировать только маленькие файлы. Причину понять я не могла, спросила как сделали другие и воспользовалась подсказкой. Лабу перепишу и залью новый вариант.

**Comment by TrofimovaEkaterina** [comment]
Переписала

**Comment by pavel-b-novikov** [comment]
Ладно, идет
